//  @ts-check

import { tanstackConfig } from '@tanstack/eslint-config'

export default [
  ...tanstackConfig,
  {
    ignores: [
      '.output/**', // Build artifacts
      'src/types/database.ts', // Auto-generated by Supabase CLI
      '*.config.js', // JS config files not in TS project
    ],
  },
]
