/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedBudgetSubscriptionsRouteImport } from './routes/_authenticated/budget/subscriptions'
import { Route as AuthenticatedBudgetReportsRouteImport } from './routes/_authenticated/budget/reports'
import { Route as AuthenticatedBudgetCalendarRouteImport } from './routes/_authenticated/budget/calendar'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedBudgetSubscriptionsRoute =
  AuthenticatedBudgetSubscriptionsRouteImport.update({
    id: '/budget/subscriptions',
    path: '/budget/subscriptions',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedBudgetReportsRoute =
  AuthenticatedBudgetReportsRouteImport.update({
    id: '/budget/reports',
    path: '/budget/reports',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedBudgetCalendarRoute =
  AuthenticatedBudgetCalendarRouteImport.update({
    id: '/budget/calendar',
    path: '/budget/calendar',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/login': typeof LoginRoute
  '/': typeof AuthenticatedIndexRoute
  '/budget/calendar': typeof AuthenticatedBudgetCalendarRoute
  '/budget/reports': typeof AuthenticatedBudgetReportsRoute
  '/budget/subscriptions': typeof AuthenticatedBudgetSubscriptionsRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/': typeof AuthenticatedIndexRoute
  '/budget/calendar': typeof AuthenticatedBudgetCalendarRoute
  '/budget/reports': typeof AuthenticatedBudgetReportsRoute
  '/budget/subscriptions': typeof AuthenticatedBudgetSubscriptionsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/budget/calendar': typeof AuthenticatedBudgetCalendarRoute
  '/_authenticated/budget/reports': typeof AuthenticatedBudgetReportsRoute
  '/_authenticated/budget/subscriptions': typeof AuthenticatedBudgetSubscriptionsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/login'
    | '/'
    | '/budget/calendar'
    | '/budget/reports'
    | '/budget/subscriptions'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/'
    | '/budget/calendar'
    | '/budget/reports'
    | '/budget/subscriptions'
  id:
    | '__root__'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/'
    | '/_authenticated/budget/calendar'
    | '/_authenticated/budget/reports'
    | '/_authenticated/budget/subscriptions'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/budget/subscriptions': {
      id: '/_authenticated/budget/subscriptions'
      path: '/budget/subscriptions'
      fullPath: '/budget/subscriptions'
      preLoaderRoute: typeof AuthenticatedBudgetSubscriptionsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/budget/reports': {
      id: '/_authenticated/budget/reports'
      path: '/budget/reports'
      fullPath: '/budget/reports'
      preLoaderRoute: typeof AuthenticatedBudgetReportsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/budget/calendar': {
      id: '/_authenticated/budget/calendar'
      path: '/budget/calendar'
      fullPath: '/budget/calendar'
      preLoaderRoute: typeof AuthenticatedBudgetCalendarRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedBudgetCalendarRoute: typeof AuthenticatedBudgetCalendarRoute
  AuthenticatedBudgetReportsRoute: typeof AuthenticatedBudgetReportsRoute
  AuthenticatedBudgetSubscriptionsRoute: typeof AuthenticatedBudgetSubscriptionsRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedBudgetCalendarRoute: AuthenticatedBudgetCalendarRoute,
  AuthenticatedBudgetReportsRoute: AuthenticatedBudgetReportsRoute,
  AuthenticatedBudgetSubscriptionsRoute: AuthenticatedBudgetSubscriptionsRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
